-- Unified Inventory/Kardex master import context and product/provider metadata.

ALTER TABLE suppliers
  ADD COLUMN IF NOT EXISTS code text;

UPDATE suppliers
SET code='PROV-'||upper(substr(replace(id::text,'-',''),1,8))
WHERE code IS NULL OR btrim(code)='';

CREATE UNIQUE INDEX IF NOT EXISTS suppliers_org_code_idx
  ON suppliers(organization_id,upper(code))
  WHERE code IS NOT NULL;

CREATE OR REPLACE FUNCTION cmms_supplier_default_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.code IS NULL OR btrim(NEW.code)='' THEN
    NEW.code := 'PROV-'||upper(substr(replace(NEW.id::text,'-',''),1,8));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS suppliers_default_code ON suppliers;
CREATE TRIGGER suppliers_default_code
BEFORE INSERT OR UPDATE OF code ON suppliers
FOR EACH ROW EXECUTE FUNCTION cmms_supplier_default_code();

ALTER TABLE inventory_items
  ADD COLUMN IF NOT EXISTS subcategory text,
  ADD COLUMN IF NOT EXISTS brand text,
  ADD COLUMN IF NOT EXISTS model text,
  ADD COLUMN IF NOT EXISTS barcode text,
  ADD COLUMN IF NOT EXISTS reference_price numeric(14,2) NOT NULL DEFAULT 0 CHECK (reference_price >= 0),
  ADD COLUMN IF NOT EXISTS tax_rate numeric(6,3) NOT NULL DEFAULT 0 CHECK (tax_rate >= 0 AND tax_rate <= 100);

CREATE INDEX IF NOT EXISTS inventory_items_barcode_idx
  ON inventory_items(organization_id,barcode)
  WHERE barcode IS NOT NULL AND barcode<>'';

ALTER TABLE inventory_transactions
  ADD COLUMN IF NOT EXISTS source_movement_id text;

CREATE UNIQUE INDEX IF NOT EXISTS inventory_transactions_source_movement_idx
  ON inventory_transactions(organization_id,source_movement_id)
  WHERE source_movement_id IS NOT NULL AND source_movement_id<>'';

ALTER TABLE bulk_import_batches
  ADD COLUMN IF NOT EXISTS import_number bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS origin text NOT NULL DEFAULT 'global'
    CHECK (origin IN ('global','supplier')),
  ADD COLUMN IF NOT EXISTS context_supplier_id uuid REFERENCES suppliers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS commit_scope text NOT NULL DEFAULT 'all'
    CHECK (commit_scope IN ('all','context_only')),
  ADD COLUMN IF NOT EXISTS omitted_rows integer NOT NULL DEFAULT 0 CHECK (omitted_rows >= 0);

CREATE UNIQUE INDEX IF NOT EXISTS bulk_import_batches_import_number_idx
  ON bulk_import_batches(import_number);

DROP INDEX IF EXISTS bulk_import_batches_committed_hash_idx;

CREATE UNIQUE INDEX IF NOT EXISTS bulk_import_batches_committed_scope_hash_idx
  ON bulk_import_batches(
    organization_id,
    entity,
    file_hash,
    commit_scope,
    COALESCE(context_supplier_id,'00000000-0000-0000-0000-000000000000'::uuid)
  )
  WHERE status='committed';
